quizapp/quiz/models.py
from quizapp import db

class Question(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    question = db.Column(db.String(200),nullable=False)
    answers = db.relationship("Answer",backref='author',lazy=True)

class Answer(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    answer = db.Column(db.String(20),nullable=False)
    isCorrect = db.Column(db.Boolean,default=False)
    questions = db.Column(db.Integer, db.ForeignKey('question.id'),nullable=False)

quizapp/__init__.py
from flask import Flask
from flask_sqlalchemy  import SQLAlchemy

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///site.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.secret_key = 'hello world'
db = SQLAlchemy(app)

from quizapp.auth.routes import auth
from quizapp.quiz.routes import quiz

app.register_blueprint(auth)
app.register_blueprint(quiz)

quizapp/quiz/routes.py
from flask import Blueprint, render_template, request, redirect, flash

from  .models import Answer,Question

quiz = Blueprint('quiz',__name__)


@quiz.route('/',methods=['GET'])
def questions():
    questions = Question.query.all()
    answers = Answer.query.all()
    return render_template('quiz/index.html',questions=questions,answers=answers)


@quiz.route('/',methods=['POST'])
def check():
    if request.method == "POST":
        questions = list(dict(request.form))
        questionAndAnswers = []
        correct = 0
        for question in questions:
            object = {'questionId':int(question),'answerId':int(request.form[question])}
            questionAndAnswers.append(object)
            if Answer.query.filter_by(questions=int(question),id=int(request.form[question])).first().isCorrect:
                correct+=1
        flash(f"You have {correct} correct answers", 'info')
        questions = Question.query.all()
        answers = Answer.query.all()
        return render_template('quiz/index.html', questions=questions, answers=answers,written=questionAndAnswers)

quizapp/templates/quiz/index.html
<html>
    <head>
        <title>Quiz</title>
    </head>
    <body>
        <h1>Quiz</h1>

        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <form method="post" action="{{ url_for('quiz.check') }}" enctype="multipart/form-data">
            {% for question in questions %}
                {% set outer_loop = loop %}
                <p>{{ question.id }}.{{ question.question }}</p>
                {%for answer in question.answers %}
                    <input type="radio"
                            {% if written %}
                                {%if written[outer_loop.index-1]['answerId'] == answer.id %}
                                    checked
                                {% endif %}
                            {% endif %}
                           name="{{ question.id }}" value="{{ answer.id }}">

                     <label for="{{ answer.id }}">{{ answer.answer }}</label>
                {% endfor %}
                <br>
            {% endfor %}
            <input type="submit" value="Check">
        </form>
    </body>
</html>